name: offline_lead_capture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  excel: ^1.0.9
  path_provider: ^1.6.11
  bloc_pattern: ^2.5.1
  menu_button: ^1.2.1
  rxdart: ^0.23.0
  open_file: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true